### ISSUE TITLE
re: proxysql & mariadb proxysql-binlog-reader 

### ISSUE THREAD

**Issue by ajgiles** [timo-schluessler/proxysql-binlog-reader#1]
Hello, 

Apologies for contacting you in this method, didn't see contact information in your profile. If you don't mind, I'd like to pick your brain about this. 

Came across your PR here: https://github.com/sysown/proxysql/pull/3978 

I see that you say you're using this in production and it's working. I have: 
- built your proxysql branch 'wait-for-gtid' & your proxysql-binlog-reader and have them running
- added primary & replica backends, confirmed read only tests are working and putting them in the correct hostgroups
- query rule sending all selects to the reader group & set gtid_from_hostgroup to the writer hostgroup in mysql_query_rules 
- I see the correct GTID being tracked in `stats_mysql_gtid_executed`

When running tests the read/write split "works", but am still getting stale reads. Looking at stats_mysql_connection_pool I see that Queries_GTID_sync is 0 for both hosts. 

1. Is there some additional configuration within ProxySQL I'm missing? 
2. How do you build your ProxySQL? (I used the existing proxysql docker workflow, centos7 wouldn't build, but almalinux9 did) 
3. Would you be able to share your MariaDB configs or just the relevant settings for this to work? 

Any guidance would be greatly appreciated, fully understood if you don't have the time or desire to comment. 

Thanks,

**Comment by timo-schluessler** [comment]
No issue.

1. Did you specify `default_session_track_gtids="MARIADB"`?
2. I build it using a standard debian container and by invoking `make`. Not sure whether it needed some `configure` before. In my opinion, the ‚official’ build system is a little bit strange.
3. No special MariaDB config is required - and as your proxysql instance already receives the latest executed GTIDs this part seems to wiek fine. Nevertheless these are the settings I use:
```
[mariadb]
log_bin
binlog_format=mixed
gtid_strict_mode=1
log_slave_updates=1
…
[mysqld]
expire_logs_days        = 10
max_binlog_size        = 100M
```

Did you spot the quick‘n‘dirty differentiation between proxysql-instance-wide read/write consistency and the connection-wide one?Maybe try and add an offset of one million to your `gtid_from_hostgroup` value which makes it instance-wide (we use this for pools where a read from any connection should wait for writes from any other).
If this does not help, the log output might do so.

**Comment by ajgiles** [comment]
Thanks a lot. 

1. I set it to whatever the ProxySQL docs said, so missed that. 'MARIADB' got my initial tests working, excellent. 
2. Since 1. got it working will assume the build isn't the issue. Agreed it's a little odd. 
3. Gotcha, thanks. 

```
Did you spot the quick‘n‘dirty differentiation between proxysql-instance-wide read/write consistency and the connection-wide one?Maybe try and add an offset of one million to your gtid_from_hostgroup value which makes it instance-wide (we use this for pools where a read from any connection should wait for writes from any other).
```
Doing this got my more aggressive testing to work as we need it, fantastic. 

I'll update the ProxySQL PR saying that it's working for me, hopefully will get them to pay some attention to it. 

Thanks again!
